'''
Given two strings s and t which consist of only lowercase letters.
String t is generated by random shuffling string s and then add one more letter at a random position.
Find the letter that was added in t.
Example:
Input:s = "abcd"
t = "abcde"
Output:eExplanation:
'e' is the letter that was added.

Python代码

方法1：
'''
def findTheDifference(s, t):
    for letter in t:
        if t.count(letter) > s.count(letter):
            return letter

'''
方法2：
'''
def findTheDifference(s, t): 
    return (Counter(t) - Counter(s)).popitem()[0]
